= Algorithms



An *algorithm* is a step-by-step process, defined by a set of
instructions to be executed sequentially to achieve a specified task producing
a determined output.

Examples of common discrete mathematics algorithms include:

* Searching  Algorithms to search  for an item in a data set or data structure like a tree.
* Sorting Algorithms to sort items in a specific  order.
* Insertion and Deletion  Algorithms to insert or delete item in a data structure such as a tree or list.
* Division Algorithms such as a procedure for dividing two integers or the Euclidean Algorithm to determine  the greatest common divisor between two  integers.
* Optimization algorithms such as finding the line of best fit of set of points, or the problem of finding the nearest neighbor in a set of points to a given point  (here close could mean most similar according to some mathematically defined measure of closeness or similarity)

== Structure of Algorithms in Pseudocode

While the algorithms we describe are implemented in the Python programming language, we also provide an overview of pseudocode syntax here. Pseudocode is used to provide high level description of a program or algorithm intended to be more human understandable than computer or program language. Its syntax preserves the structure of the program or algorithm while ignoring programming language specific details. It is meant to be easier to read and analyze.  Often, in designing an algorithm for language specific implementation, a pseudocode implementation is obtained first.  In addition to coming early in the design of a computer program, pseudocode also has two other important uses:

. It can be used to help non-programmers understand what a program or algorithm does and how it works.

. It can be used for debugging purposes when a programmer is trying to debug and solve a logic error in a computer program as it is closer to human language. Defects can be easier to find in a program implementation by analyzing the sequence of implementation steps in the pseudocode description.

[NOTE]
====
Many of the terms in this section were also discussed in link:python_intro.html#_introduction_to_python[Introduction to Python].
====

Recall that an algorithm is a process of finite sequences of instructions used to solve a problem or obtain a result of a computation.
The key features of an algorithm include:

* Input
* Variables
* Data and data types
* Instructions or statements
* Output

.Pseudocode Example
[%header,cols="1a,1a"]
|===
|Pseudo Code
|Python Code

|[source, pseudocode, subs="normal, verbatim"]
----
*procedure* search(_{a~1~, a~2~, ..., a~n~}, x_) //<1>
*begin* //<2>
	*for* _i_ = 1 *to* _n_ *do* //<3>
		*if* _a~i~_ equals _x_ *then* //<4>
			*return* _i_ //<5>
		*end if*
	*end for*
	*return* -1
*end* //<6>
----
<1> Define a new _procedure_ with inputs
<2> Explicitely start each _block_
<3> Loop _block_ using a sequence of integers
<4> Conditionally execute _block_
<5> Return (exit) from _procedure_ with specific value
<6> Explicitely end each _block_
|[source, python]
----
def search(a, x): //<1>
	for i in range(0, len(a)): //<2>
		if a[i] == x: //<3>
			return i //<4>
	return -1
<5>
----
<1> Define a new _function_ and start its _block_ with a *:*
<2> Loop _block_ using a sequence of integers
<3> Conditionally execute _block_
<4> Return (exit) from _function_ with specific value
<5> Each _block_ of code ends with unindent
|===

== Examples of Algorithms
We now proceed to develop some algorithms beginning with algorithms for common mathematical
operations.  Much of mathematical notation can be considered pseudocode.

=== Sum Notation
Consider the sum

$Sum=a_1+a_2+\ldots+a_n=\sum_{i=1}^{n}a_i,$

which is a description of adding using the index $i$, the numbers $a_i$,
running from $i=1$ to $i=n$.

:pt_code_height: 370
:pt_rawinput: false
:pt_code:  def%20Sum_Notation%28a,%20n%29%3A%0A%20%20%20%20sum%20%3D%200%0A%20%20%20%20for%20i%20in%20range%280,%20n%29%3A%0A%20%20%20%20%20%20%20%20sum%20%3D%20sum%20%2B%20a%5Bi%5D%0A%20%20%20%20return%20sum%0A%20%20%20%20%0AS%20%3D%20Sum_Notation%28%5B1,%204,%209,%2016,%2025%5D,%203%29%0Aprint%28%22Sum%20of%20first%203%20nums%3A%22,%20S%29%0A
****
.Example {counter:algoex} - Sum Notation in Python
--
--

The Python code below uses a *for* loop to implement sum notation, adding the first $n$ terms of a sequence $a=(a_i)$.

include::python_tutor.adoc[]
****

=== Exponentiation
Suppose we want to evaluate $b^n$, with base $b>0$, and exponent,
$n$ a positive integer.
For example to evaluate $5^6$, we could multiply iteratively, 5,

$1, 5, 5\times5, 5\times5\times5, 5\times5\times5\times5,$ etc .

:pt_code_height: 370
:pt_rawinput: false
:pt_code: def%20Exponentiation%28n,%20b%29%3A%0A%20%20%20%20Power%20%3D%201%0A%20%20%20%20for%20i%20in%20range%280,%20n%29%3A%0A%20%20%20%20%20%20%20%20Power%20%3D%20b%20*%20Power%0A%20%20%20%20return%20Power%0Ap%20%3D%20Exponentiation%285,%203%29%0Aprint%28%223%20raised%20to%205th%20power%3A%22,%20p%29%0A
****
.Example {counter:algoex} - Exponentiation in Python
--
--

The Python code below uses a *for* loop to implement exponentiation,
multiplying a positive base $b$ with itself $n$ times.

include::python_tutor.adoc[]
****


=== Factorial
The *factorial* of a positive integer $n$ can be computed iteratively. For example $4!$ can be calculated as

$1,  1\times2, 1\times2\times3, 1\times2\times3\times4.$



:pt_code_height: 350
:pt_rawinput: false
:pt_code: def%20factorial%28n%29%3A%0A%20%20%20%20result%20%3D%201%0A%20%20%20%20for%20i%20in%20range%281,%20n%20%2B%201%29%3A%0A%20%20%20%20%20%20%20%20result%20%3D%20result%20*%20i%0A%20%20%20%20return%20result%0A%0Af%20%3D%20factorial%286%29%0Aprint%28%226%20factorial%3A%22,%20f%29%0A
****
.Example {counter:algoex} - Factorial ($n!$) in Python
--
--
The Python code below uses a *for* loop to implement $n!$ by iteratively multiplying.

include::python_tutor.adoc[]
****


=== Find Minimum in a List of Integers
Consider an algorithm to determine the minimum element in a finite sequence or
list of integers.

The algorithm would be constructed as follows:


* We define a variable $min$ and assign it to the first indexed element in the list.

* Traverse along  the list to the next indexed element and compare that
indexed element in the list with the currently assigned value of the variable $min$.
If the inspected element is smaller than the currently assigned value of $min$,
then update the value of $min$.
* Repeat the previous step if there are more elements in the list to inspect and compare.
* Stop when the entire list has been traversed and all elements in the list
have been inspected and compared against the variable $min$.



A Python implementation of finding the minimum in a set of $n$ integers is given below.

:pt_code_height: 380
:pt_rawinput: false
:pt_code: def%20minimum%28a%29%3A%0A%20%20%20%20min%20%3D%20a%5B0%5D%0A%20%20%20%20for%20i%20in%20range%280,%20len%28a%29%29%3A%0A%20%20%20%20%20%20%20%20if%20a%5Bi%5D%20%3C%20min%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20min%20%3D%20a%5Bi%5D%0A%20%20%20%20return%20min%0A%0Am%20%3D%20minimum%28%5B3,%202,%201,%205,%20-4,%206%5D%29%0Aprint%28%22The%20minimum%20is%22,%20m%29
****
.Example {counter:algoex} - Minimum in Python
--
--
The Python code below uses a *for* loop to implement an algorithm to find the minimum in a set of $n$ integers.

include::python_tutor.adoc[]
****

== The Linear Search Algorithm
A linear search algorithm involves searching for a target integer $x$ in a list of
distinct integers $ (a_1, a_2, ..., a_n)$, and returns the location $i$ in the list that the
target element $x$ is found or returns a value indicating that the target element $x$ is not
in the list $ (a_1, a_2, ..., a_n)$.


A Python implementation of the linear search algorithm is given below.

:pt_code_height: 370
:pt_rawinput: false
:pt_code: def%20Linear_Search%28a,%20x%29%3A%20%0A%20%20%20%20for%20i%20in%20range%280,%20len%28a%29%29%3A%20%0A%20%20%20%20%20%20%20%20if%20a%5Bi%5D%20%3D%3D%20x%3A%20%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20i%20%0A%20%20%20%20return%20-1%0A%0Aindex%20%3D%20Linear_Search%28%5B6,%203,%204,%205,%207%5D,%204%29%0Aprint%28%224%20found%20at%20index%22,%20index%29%0A
****
.Example {counter:algoex} - Linear Search Algorithm in Python
--
--
The Python code below uses a *for* loop to implement the linear search algorithm.  The algorithm returns the position $i$
of the list where the target $x$ is found, returning $-1$ if the target is not in the list.


include::python_tutor.adoc[]
****

== The Bubble Sort Algorithm
The bubble sort algorithm is a simple  sorting procedure.  It is typically used to sort  an array of $n$ data elements in either increasing or decreasing order.  We describe the bubble sort algorithm for arranging a list of $n$ real numbers in increasing order.

* The algorithm compares the first two elements of the array and swaps them if they are out of order.
* It continues by traversing up the array comparing each pair of adjacent elements and swaps them if they are out of order until we reach the last entry in the array at location $n$.
* The last entry in the array will then be the largest element of the original list.
* After the largest element has been sorted into position $n$, the algorithm continues by again comparing the first two elements and
swapping if they are out of order.
* Continue traversing the array and comparing and swapping adjacent elements that are out of order until position $n-1$ of the array, after which the 2nd largest element is in position $n-1$. The elements, now at positions $n$, and $n-1$, are sorted.
* Continue to sort at positions $n-2$, then $n-3$ until position $1$.


A Python implementation of the bubble sort algorithm is given below.

:pt_code_height: 450
:pt_rawinput: false
:pt_code: def%20BubbleSort%28a%29%3A%0A%20%20%20%20n%20%3D%20len%28a%29%0A%20%20%20%20for%20i%20in%20range%280,%20n%29%3A%0A%20%20%20%20%20%20%20%20%20for%20j%20in%20range%280,%20n%20-%20i%20-%201%29%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20if%20a%5Bj%5D%20%3E%20a%20%5Bj%2B1%5D%20%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20temp%20%3D%20a%5Bj%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20a%5Bj%5D%20%3D%20a%5Bj%2B1%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20a%5Bj%2B1%5D%20%3D%20temp%0A%20%20%20%20return%20a%0A%0Aarr%20%3D%20BubbleSort%28%5B6,%202,%205,%203,%204,%201%20%5D%29%0Aprint%28%22Sorted%20array%20is%3A%22,%20arr%29%0A
****
.Python implementation of the Bubble Sort Algorithm
--
--
The Python code below uses two *for* loops to implement the Bubble Sort as found in the pseudocode description.

include::python_tutor.adoc[]
****

****
.Example {counter:algoex} - Tracing a Bubble Sort
As an example we consider explicitly the steps of the Bubble Sort Algorithm to sort $6, 2, 5, 3, 4, 1, $ in increasing
order.

.Solution


First Pass

$\left(\mathbf{6}\ \mathbf{2}\ 5\ 3\ 4\ 1\right)\rightarrow\ \left(\mathbf{2}\ \mathbf{6}\ 5\ 3\ 4\ 1\right)\ $ compare and swap

$\left(2\ \mathbf{6}\ \mathbf{5}\ 3\ 4\ 1\right)\rightarrow\ \left(2\ \mathbf{5}\ \mathbf{6}\ 3\ 4\ 1\right)\ $ compare and swap

$\left(2\ 5\ \mathbf{6}\ \mathbf{3}\ 4\ 1\right)\rightarrow\ \left(2\ 5\ \mathbf{3}\ \mathbf{6}\ 4\ 1\right)\ $ compare and swap

$\left(2\ 5\ 3\ \mathbf{6}\ \mathbf{4}\ 1\right)\rightarrow\ \left(2\ 5\ 3\ \mathbf{4}\ \mathbf{6}\ 1\right)\ $ compare and swap

$\left(2\ 5\ 3\ 4\ \mathbf{6}\ \mathbf{1}\right)\rightarrow\ \left(2\ 5\ 3\ 4\ \mathbf{1}\ \mathbf{6}\right)\ $ compare and swap

Second pass

$\left(\mathbf{2}\ \mathbf{5}\ 3\ 4\ 1\ 6\right)\rightarrow\ \left(\mathbf{2}\ \mathbf{5}\ 3\ 4\ 1\ 6\right)\ $ compare and no swap

$\left(2\ \mathbf{5}\ \mathbf{3}\ 4\ 1\ 6\right)\rightarrow\ \left(2\ \mathbf{3}\ \mathbf{5}\ 4\ 1\ 6\right)\ $ compare and swap

$\left(2\ 3\ \mathbf{5}\ \mathbf{4}\ 1\ 6\right)\rightarrow\ \left(2\ 3\ \mathbf{4}\ \mathbf{5}\ 1\ 6\right)\ $ compare and swap

$\left(2\ 3\ 4\ \mathbf{5}\ \mathbf{1}\ 6\right)\rightarrow\ \left(2\ 3\ 4\ \mathbf{1}\ \mathbf{5}\ 6\right)\ $ compare and swap

Third pass

$\left(\mathbf{2}\ \mathbf{3}\ 4\ 1\ 5\ 6\right)\rightarrow\ \left(\mathbf{2}\ \mathbf{3}\ 4\ 1\ 5\ 6\right)\ $ compare and no swap

$\left(2\ \mathbf{3}\ \mathbf{4}\ 1\ 5\ 6\right)\rightarrow\ \left(2\ \mathbf{3}\ \mathbf{4}\ 1\ 5\ 6\right)\ $ compare and no swap

$\left(2\ 3\ \mathbf{4}\ \mathbf{1}\ 5\ 6\right)\rightarrow\ \left(2\ 3\ \mathbf{1}\ \mathbf{4}\ 5\ 6\right)\ $ compare and swap


Fourth Pass

$\left(\mathbf{2}\ \mathbf{3}\ 1\ 4\ 5\ 6\right)\rightarrow\ \left(\mathbf{2}\ \mathbf{3}\ 1\ 4\ 5\ 6\right)\ $ compare and  no swap

$\left(2\ \mathbf{3}\ \mathbf{1}\ 4\ 5\ 6\right)\rightarrow\ \left(2\ \mathbf{1}\ \mathbf{3}\ 4\ 5\ 6\right)\ $ compare and swap


Fifth Pass


$\left( \mathbf{2}\ \mathbf{1}\ 3\ 4\ 5\ 6)\rightarrow\ (\mathbf{1}\ \mathbf{2}\ 3\ 4\ 5\ 6)\right)\ $ compare and swap
****


== The Insertion Sort Algorithm

The insertion sort works by working through a list and classifying two pieces as sorted and unsorted.

* The insertion sort scans through each element of the list
using an outer loop with a variable, say $i$.

* At each stage, the list is divided into a sorted section, say the left section, and a section that is not sorted, say the right.

* The location up to which the list is sorted, is denoted by a pointer or index, called a key.

* At the current stage, the next element from the unsorted section, on the right,
is inserted into its appropriate position in the sorted section on the left.

* The process of inserting smaller elements in the left involves shifting,
larger elements to the right, using a variable, say $j$.


A Python implementation of the Insertion Sort Algorithm is given below:

:pt_code_height: 350
:pt_rawinput: false
:pt_code:   def%20insertion_sort%28a%29%3A%0A%20%20%20%20for%20i%20in%20range%281,%20len%28a%29%29%3A%0A%20%20%20%20%20%20%20%20j%20%3D%20i-1%20%0A%20%20%20%20%20%20%20%20key%20%3D%20a%5Bi%5D%0A%20%20%20%20%20%20%20%20while%20%28a%5Bj%5D%20%3E%20key%29%20and%20%28j%20%3E%3D%200%29%3A%0A%20%20%20%20%20%20%20%20%20%20%20a%5Bj%2B1%5D%20%3D%20a%5Bj%5D%0A%20%20%20%20%20%20%20%20%20%20%20j%20-%3D%201%0A%20%20%20%20%20%20%20%20a%5Bj%2B1%5D%20%3D%20key%0A%20%0A%23%20Driver%20code%20to%20test%20above%0Aarr%20%3D%20%5B64,%2034,%2025,%2012,%2022,%2011,%2090%5D%0A%20%0Ainsertion_sort%28arr%29%0A%20%0Aprint%20%28%22Sorted%20array%20is%3A%22%29%0Afor%20i%20in%20range%28len%28arr%29%29%3A%0A%20%20%20%20print%20%28%22%25d%22%20%25arr%5Bi%5D%29,%0A
****
.Example {counter:algoex} - Insertion Sort in Python
--
--
The Python code below uses a *for* loop and a nested while loop to implement the Insertion Sort
Algorithm.

include::python_tutor.adoc[]
****

****
.Example {counter:algoex} - Tracing the Insertion Sort Algorithm


As an example we consider explicitly the steps of the Insertion Sort Algorithm to sort $6, 2, 5, 3, 4, 1, $ in increasing
order.
The key, or boundary, between the sorted and unsorted portions is denoted by the vertical bar or pipe character.

.Solution
First pass

$(\underbrace{\mathbf{6}\ |\ \mathbf{2}}\ 5\ 3\ 4\ 1)$ compare and insert

Second pass

$(2\ \underbrace{\mathbf{6}\ |\ \mathbf{5}}\ 3\ 4\ 1)$ compare and  insert

$(\underbrace{\mathbf{2}\ \mathbf{5}}\ |\ 6\ 3\ 4\ 1)$ compare and do not insert

Third pass

$(2\ 5\ \underbrace{\mathbf{6}\ |\ \mathbf{3}}\ 4\ 1)$ compare and  insert

$(2\ \underbrace{\mathbf{5}\ \mathbf{3}}\ |\ 6\ 4\ 1)$ compare and  insert

$(\underbrace{\mathbf{2}\ \mathbf{3}}\ 5\ |\ 6\ 4\ 1)$ compare and  do not insert

Fourth pass

$(2\ 3\ 5\ \underbrace{\mathbf{6}\ |\ \mathbf{4}}\ 1)$ compare and  insert

$(2\ 3\ \underbrace{\mathbf{5}\ \mathbf{4}\ }|\ 6\ 1)$ compare and  insert

$(2\ \underbrace{\mathbf{3}\ \mathbf{4}}\ 5\ |\ 6\ 1)$ compare and  do no insert

Fifth pass

$(2\ 3\ 4\ 5\ \ \underbrace{\mathbf{6}\ |\ \mathbf{1}})$    compare and  insert

$(2\ 3\ 4\ \underbrace{\mathbf{5}\ \mathbf{1}}\ |\ 6)$    compare and  insert

$(2\ 3\ \underbrace{\mathbf{4}\ \mathbf{1}}\ 5\ |\ 6)$    compare and  insert

$(2\ \underbrace{\mathbf{3}\ \mathbf{1}}\ 4\ \ 5\ |\ 6)$    compare and  insert

$(\underbrace{\mathbf{2}\ \mathbf{1}\ }3\ 4\ \ 5\ |\ 6)$    compare and  insert

$( 1\ 2\ 3\ 4\ \ 5\ |\ 6)$
****

== The Binary Search Algorithm
The binary search algorithm searches a *sorted* array of integers for a target value $t$.  The algorithms looks for $t$ in the middle of the array.  If it does not find $t$ in the middle, it considers either the first half or the second half.  It continues recursively splitting the search space in half until it either finds $t$ or fails.


:pt_code_height: 520
:pt_rawinput: false
:pt_code: from%20math%20import%20floor%0Adef%20BinarySearch%28a,%20t%29%3A%0A%20%20%20%20L%20%3D%200%0A%20%20%20%20R%20%3D%20len%28a%29%20-%201%0A%20%20%20%20while%20L%20%3C%3D%20R%3A%0A%20%20%20%20%20%20%20%20m%20%3D%20floor%28%28L%20%2B%20R%29%20/%202%29%0A%20%20%20%20%20%20%20%20if%20a%5Bm%5D%20%3C%20t%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20L%20%3D%20m%20%2B%201%0A%20%20%20%20%20%20%20%20elif%20a%5Bm%5D%20%3E%20t%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20R%20%3D%20m%20-%201%0A%20%20%20%20%20%20%20%20else%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20m%0A%20%20%20%20return%20-1%0A%0Ai%20%3D%20BinarySearch%28%5B200,%20205,%20315,%20498%5D,%20498%29%0Aprint%28%22498%20is%20at%20index%22,%20i%29
****
.Example {counter:algoex} - Binary Search Algorithm in Python
--
--

include::python_tutor.adoc[]
****

== Algorithmic Complexity of Common Algorithms

In this section we give time complexity using big 0 notation of some of the important algorithms in this section.
Recall big $O$ notation is used to quantify the worst case an algorithm performs on a data input size of n.

=== The Linear Search Algorithm is $O(n)$.

The linear search algorithm iterates across a list of $n$ data elements. If the first element in the list is the target
element, the algorithm stops. Otherwise, move to the next element and continue
repeatedly until the target element is found or not.  If the target element is not in
the search list the algorithm exhaustively searches through every single element.

This is the
worst case scenario with linear search in which the algorithm inspects every single element,
either because the target element is the last element of the array,
or the target element  is not  actually  in the search list at all. The algorithm
runs in $O(n)$ time in the worst case.


=== The Bubble Sort and Insertion Sort Algorithms are $O(n^2)$.

We analyze the bubble sort algorithm beginning with a concrete list of size $n=5$ and
generalize the analysis.

Consider the case of a list of size $n=5$. The naive bubble sort algorithm in this case will
involve 4 passes.

In the first pass, there will be 4 comparisons and up to 4 swaps, after which
the element in position 5 is in its correct position.

In the second pass, there will be 3 comparisons and up to 3 swaps, after which
the element in position 4 is in its correct position.

In the third  pass, there will be 2 comparisons and up to 2 swaps, after which
the element in position 3 is in its correct position.

In the fourth pass, there will be 1 comparison and one possible swap , after which
both the elements in positions 1 and 2 are both in their correct positions.

Adding the comparisons from each pass we obtain,

$4+3+2+1=1+2+3+4$.

In general, if the list is of size $n$, there will be $n-1$ passes with swaps,

$n-1+n-2+...3+2+1 = 1+2+3+...+n-1$.

We will show later, that

$ 1+2+3+\cdots+n-1= \frac{(n-1)\cdot\ n}{2}=\frac{n^2}{2}-\frac{n}{2}$, which is $O(n^2)$.

It is left as an exercise to verify that the insertion sort algorithm is $O(n^2)$.

=== The Binary  Search Algorithm is $O(\log{n})$.

The binary search algorithm searches for a target element $x$  in a list of $n$ elements
by comparing the middle element in the the sorted data set with the target $x$. The algorithm
stops if the middle element $a_m$ is  the target element. Otherwise the search continues with
half the data set--the half to the left if the middle element is larger than the target $x$
or the half to the right if the middle element is smaller than the target.

The number of steps in the binary search then is the number of times we have to split the data set until we locate the target
element, or determine that the target element is not in the search list after splitting down to 1 element.

The number of times we need to split the data set of size $n$, in the worst case then, is $p$ which is
found by solving the exponential equation,

$2^p = n$.

The algorithm then is $O(p)$.

The solution of the exponential equation, $2^p = n$, is in log form,

$p=\log_2{n}$.

The binary search algorithm then is $O(p)=O(\log{n})$.

== Exercises

////
. The selection sort algorithm is another algorithm to sort a list of $n$ elements.
It finds the smallest element in the list and exchanges it with whatever is in
position $1$ of the list. It then finds the next smallest integer, and exchanges it
with whatever is in position $2$ of the list, continuing in this way until the entire
list has been sorted.

.. Apply the selection sort algorithm to the following list of integers, showing each
of the steps, or passes, involving comparisons and swaps.
+
${4,8,3,10,7,2,6 ,9,5,1}$
.. Count the number of steps, used to sort the list, ${4,8,3,10,7,2,6 ,9,5,1}$, using the selection sort
method.
.. Devise an algorithm in pseudocode to implement the selection sort algorithm.
.. Explain why the selection sort algorithm, in the worst case is $O(n^2)$.
You may use the formula $1+2+3…+n=\frac{n(n+1)}{2}$, or a variation of it.
////

. Explain why the insertion sort algorithm is $O(n^2)$.

. Estimate the time complexity for each of the following two algorithms
by first counting the number of steps, and summarizing your findings using
big O notation
.. An algorithm to find the sum and product of $n$ integers from
$1$ to $n$.


+
++++
<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=Generator content="Microsoft Word 15 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0in;
	margin-right:0in;
	margin-bottom:8.0pt;
	margin-left:0in;
	line-height:106%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
.MsoChpDefault
	{font-size:10.0pt;
	font-family:"Calibri",sans-serif;}
.MsoPapDefault
	{margin-bottom:8.0pt;
	line-height:106%;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->
</style>

</head>

<body lang=EN-US>

<div class=WordSection1>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>procedure</b>
Sum_Product_i(n)</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>begin</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>                 sum
=0</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;
            product=1</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;             <b>for</b>
i =1 &nbsp;to n <b>do</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                       sum=sum + i</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              product=product*i</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>&nbsp;&nbsp;&nbsp;&nbsp;
          end</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>end</b></p>

<p class=MsoNormal>&nbsp;</p>

</div>

</body>

</html>

++++

.. A procedure to create a matrix $A_{n,n}$, with $n$ rows and $n$ columns,
with the entry $m$ in row $i$ and column $j$.
+
++++
<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=Generator content="Microsoft Word 15 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin-top:0in;
	margin-right:0in;
	margin-bottom:8.0pt;
	margin-left:0in;
	line-height:105%;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
.MsoChpDefault
	{font-size:10.0pt;}
.MsoPapDefault
	{margin-bottom:8.0pt;
	line-height:105%;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->
</style>

</head>

<body lang=EN-US>

<div class=WordSection1>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>procedure</b>
Create_Matrix(n)</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>begin</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<b>for</b> i =1 &nbsp;to n <b>do</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<b>for </b>j =1 &nbsp;to n <b>do</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
A[i,j]=m</p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
end</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; end</b></p>

<p class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b>end</b></p>

<p class=MsoNormal>&nbsp;</p>

</div>

</body>

</html>


++++
. Explain how the binary search algorithm can be modified or used
to insert a new integer element $x$ into a sorted list of $n$ integers.


. Write a recursive  procedure in pseudocode to implement the binary search algorithm.


. A binary string of length n is a sequence of $0^\prime s$ and $1^\prime s$ of length $n$.
For example, the binary strings of length two are $00, 01, 10,$ and $11$, and the binary strings of
length three are $000, 001, 010, 011, 100, 101, 110,$ and $111$. Write a recursive algorithm in
pseudocode to generate all binary strings of length $n$.


. Write recursive procedures in pseudocode to generate the following sequences, all of which are variations of the Fibonacci sequence,

.. $a_1 =1, a_2 = 1,$ and $a_n = a_{n-1}+2a_{n-2}.$

.. $b_1 = 2, b_2 = 3,$ and $b_n = b_{n-1}\cdot\ b_{n-2}$


.. $c_1 = 5$ and $c_n = {2c}_n+n$

. Recall that the median of an ordered set of numbers $\left\{a_1,a_2,\ldots,\ a_n\right\}$ is the number in the middle of the set.
If the sorted set has an odd number of elements, then
the median is $a_M$, where $M=\left\lceil \frac{n}{2}\right\rceil$.
For example, the set $a_1=10,\ a_2=10,\ a_3=7,\ a_4=6,\ a_5=2$ has median
$a_3=7$.
+
If the sorted set has an even number of elements, then
the median  $a_M$  is the mean of $a_\frac{n}{2}$  and $a_{\frac{n}{2}+1}$.
For example,  the set $a_1=10,\ a_2=10,\ a_3=7,\ a_4=6,\ a_5=2,\ a_6=0$ has median $\frac{\left(a_3+a_4\right)}{2}=\frac{7+6}{2}=6.5.$
+
Write an algorithm in pseudocode to calculate the median of a data set by first sorting in decreasing order.

. The range of a set of  integers ${a_1,a_2,\ldots, a_n}$ is the maximum value minus the minimum value,
$range={a}_{max}-{a}_{min}$.
.. Give an algorithm to find the range that uses a sorting algorithm and subtracts the first element from the last element in the sorted list.
.. Give an algorithm to find the range that modifies the linear search algorithm to find both  $a_{max}$ and $a_{min}$, and then does the subtraction
${a}_{max}-{a}_{min}$.
.. Explain, using complexity analysis, which of the two algorithms is more efficient?


. Consider the following lists of integers.
+
A. $\{4,8,3,10,7,2,6,9,5,1\}$
B. $\{10,5,3,12,2,9,7,1,6,11,8,5\}$
C. $\{8,3,14,5,4,11,9,2,7,6,12,13,1,10\}$
+
Sort the lists using:

.. The insertion sort algorithm, showing all the shifts.
.. The bubble sort algorithm, showing all the swaps in the case.
.. Give a count of the steps used in the both algorithms.


. For the following lists,
+
A. $\{6,31,46,49,49,55,56,59,65,82\}$
B. $\{9,14,16,25,26,33,44,45,52,55,57,68,72,72,84,94\}$
C. $\{11,14,23,29,31,36,41,41,44,47,47,50,65,70,82,85,88,89,92,96\}$
+
Apply the binary search algorithm to search for the target $x=65$. Give a count of the number of steps involved in each search.
