= Introduction to Python

== Programming Basics

__Computers__ are programmable machines that __process information__ by manipulating data. As the data can represent any real world information, and programs can be readily changed, computers are capable of solving many kinds of problems.

=== Programming Languages and Environments

There are many different programming languages for programmers to choose from. Each language has its own advantages and disadvantages, and new languages gain popularity while older ones slowly lose ground. In this book, we use the __Python 3__ programming language. It is popular in both academia and industry, and was designed with education in mind.

=== PythonTutor
PythonTutor is an environment for creating very short and simple Python programs and visualizing their execution. This enables beginners to visually see the data as it gets manipulated by the instructions.

:pt_code_height: 370
:pt_rawinput: false
:pt_code: age%20%3D%2021%0Adays%20%3D%20365%20*%20age%0Amsg%20%3D%20%22You%20have%20lived%20this%20many%20days%3A%22%0Aprint%28msg,%20days%29%0Aage%20%3D%2041%0Adays%20%3D%20365%20*%20age%0Aprint%28msg,%20days%29%0A
****
.Example {counter:python_intro_example} - A Simple Program
--
--
Use the _Next_ button to step through the program below and watch the data get created and modified.  Notice how the arrows move to indicate what instruction the program execution is on.
include::python_tutor.adoc[]
****

=== Comments

Program files can contain source code and comments.  Comments are not instructions for the computer to follow, but instead notes for programmers to read. Comments in Python start with a pound sign (#). Anything following the pound sign that is on the same line as the pound sign will not be executed. Often, at the very beginning of a program, comments are used to indicate the author and other information. Comments are also used to explain tricky sections of code or disable code from executing.

[source, python]
----
# This line is not Python code, it is a comment.

score = 9001 # over 9000!!!

# The next line of code is disabled because is starts with a #.
# score = 8000

----

== Data Types

Programming is all about information processing. Information is categorized by data types. Four basic data types we will be considering are *int*, *float*, *bool*, and *str*. Int consists of __integers__, which are whole numbers written without a decimal point. This includes positive and negative whole numbers as well as zero. Float consists of _floating-point numbers_, which are numbers that are written with a decimal point.  Bool consists of _Boolean_ values (named after the mathematician George Boole). The only Boolean values are True and False. Str consists of _strings_, which are sequences of text characters including punctuation, symbols, and whitespace. Every value in Python has a corresponding data type. The table below shows examples of ints, floats, and strings.

.Basic Data Types
[width="50%",align="center",options="header",cols="1,2"]
|====
| Data Type | Example Values
| int | 2,  -2,  0,  834529
| float | 3.14, -2.3333, 7.0
| bool | True, False
| str| "Hello World!",  'Coconut',  "0",  '4 + 6'
|====

.Strings and Quotation Marks
[NOTE]
====
Strings are always surrounded by quotation marks. Python allows either single (') or double (") quotation marks. Some strings may look like numbers, but as long as they are surrounded by quotation marks, they are treated like text.
====

== Variables

__Variables__ are (virtual) boxes that __store__ values for reuse later. A variable has a name and a current value. Each variable can only hold one value at a time. Variables are assigned a value using the single equal sign (=). As Python executes one line at a time, variables come into existence on the line where they are first assigned. Each variable only stores the most recent value assigned to it.

:pt_code_height: 300
:pt_rawinput: false
:pt_code: a%20%3D%204%20%23%20a%20stores%204%0Ab%20%3D%20%22Hello%20World!%22%0Ac%20%3D%20False%0Ap1_points%20%3D%201337%0A
****
.Example {counter:python_intro_example} - Basic Variables and Data Types
--
--
Use the _Next_ button to step through the program below and watch the variables get created.

include::python_tutor.adoc[]
****

[NOTE]
====
.Variable Names
Variables can have complex names like __player1_score__. In general, never start a variable name with a number and never use spaces in variable names.
====

== Operators and Expressions

:pt_code_height: 390
:pt_rawinput: false
:pt_code: a%20%3D%204%20%2B%202%0Ab%20%3D%20a%20*%202%0Aa%20%3D%20100%0Ac%20%3D%2010%20-%20b%0Ad%20%3D%2010%20//%205%20%23%20int%20division%0Ae%20%3D%2011%20//%204%20%23%20the%20quotient%0Af%20%3D%2011%20%25%204%20%23%20the%20remainder%0Ag%20%3D%2011%20/%204%20%23%20Ugh!%20Decimal%20Numbers!
****
.Example {counter:python_intro_example} - Numerical Operators and Expressions
--
--
Try to predict the variable names, values, and data types in the the code below.

include::python_tutor.adoc[]
****

.Expression Evaluation
[NOTE]
====
When Python encounters a line with an expression, it always evaluates the expression first. Consider the following line of code:

[source, python]
----
x = (3 + 4) * 2

----
Python first calculates the value of the expression to the right of the equal sign by using the standard order of operations starting inside the parentheses. The value given by the above expression is calculated to be equal to 14. Then, Python creates the variable x and assigns the value 14 to this variable. The variable only stores the calculated value, not the entire expression that generated that value.
====

:pt_code_height: 500
:pt_rawinput: false
:pt_code: a%20%3D%20True%0Ab%20%3D%20False%0A%23%20or%20is%20True%20if%201%20side%20is%20True%0Ac%20%3D%20True%20or%20False%0A%23%20and%20is%20True%20if%20both%20sides%20are%20True%0Ad%20%3D%20False%20and%20True%0A%23%20not%20negates%20the%20boolean%0Ae%20%3D%20not%20%28%28c%20and%20d%29%20or%20True%29%0Ax%20%3D%2010%0Af%20%3D%20%28x%20%3E%205%29%0Ag%20%3D%20%28x%20%3C%3D%2012%29%0Ah%20%3D%20%28x%20%3D%3D%209%29%0Ai%20%3D%20%28x%20!%3D%2010%29
****
.Example {counter:python_intro_example} - Boolean Operators and Expressions
--
--
Note how each expression returns a Boolean value.  These are called *Boolean expressions*.

include::python_tutor.adoc[]
****

== Strings and Printing
Besides creating and storing values in variables, we can also output text on a screen by calling the print() function.

:pt_code_height: 320
:pt_rawinput: false
:pt_code: print%28%22Hello%20World!%22%29%0Aa%20%3D%20%22The%20answer%20is%22%0Ab%20%3D%206%20*%207%0Aprint%28a,%20b%29%0Aprint%28False,%20%22Hobbit%22,%201,%20%22Ring%22%29
****
.Example {counter:python_intro_example} - Strings and print()
--
--
Try to predict the printed output.  Look at the small window in the top-right as you use the __Next__ button.

include::python_tutor.adoc[]
****

== If Statements
A *block* of code is a collection of lines of code that are either all executed (in sequential order) or all skipped. Blocks always start with a *colon* (:) on the previous line and require every line in the block to be indented the same amount using tabs or spaces. One way in which Python can execute or skip over a block involves using an *if* command and a Boolean expression. If the expression is true, then the block executes. Othewise, the block is skipped.

:pt_code_height: 450
:pt_rawinput: false
:pt_code: print%28%22Hi.%20What%20would%20you%20like%20to%20drink%3F%22%29%0Aage%20%3D%205%0Aif%20age%20%3E%3D%2021%3A%20%23%20Block%20starts%20on%20next%20line%0A%20%20%20%20print%28%22Beer%22%29%20%23%20Block%20line%201%0A%20%20%20%20print%28%22Wine%22%29%20%23%20Block%20line%202%0Aprint%28%22Coke%22%29%0Aprint%28%22Water%22%29%0Aif%20age%20%3C%3D%208%3A%0A%20%20%20%20print%28%22Milk%22%29%0A%20%20%20%20print%28%22Juice%22%29
****
.Example {counter:python_intro_example} - If Statements
--
--
* Notice that all un-indented lines and the second block execute, while the first block does not execute.
* Which blocks execute if age = 22? What about if age = 15?

include::python_tutor.adoc[]
****

When you want to force exactly 1 of 2 blocks to execute (as opposed to just skipping a block), you can use the *else* command in addition to the if command. If the expression following the if command is true, then the first block executes. Otherwise, the second block executes.

:pt_code_height: 350
:pt_rawinput: false
:pt_code: p1%20%3D%20354%0Ap2%20%3D%20387%0Aif%20p1%20%3E%20p2%3A%0A%20%20%20%20print%28%22Player%201%20Wins!%22%29%0Aelse%3A%0A%20%20%20%20print%28%22Player%202%20Wins!%22%29%0A
****
.Example {counter:python_intro_example} - If-Else Statements
--
--
* No matter how you change the scores, only 1 print() function executes.
* Try making the scores the same.

include::python_tutor.adoc[]
****

In order to force exactly 1 of more than 2 blocks to execute, you can use the *elif* command in addition to the if and else commands. Each elif command must be followed by a Boolean expression. When using if and elif commands, each expression is checked in sequential order, and the block following the first true expression executes. If none of the expressions are true, the block following the else command is executed.

:pt_code_height: 450
:pt_rawinput: false
:pt_code: temp%20%3D%2083%0Aif%20temp%20%3E%2090%3A%0A%20%20%20%20print%28'Too%20hot!'%29%0Aelif%20temp%20%3E%2080%3A%0A%20%20%20%20print%28'A%20little%20bit%20too%20warm.'%29%0Aelif%20temp%20%3E%2070%3A%0A%20%20%20%20print%28'Just%20right.'%29%0Aelif%20temp%20%3E%2060%3A%0A%20%20%20%20print%28'A%20little%20bit%20too%20cool.'%29%0Aelse%3A%0A%20%20%20%20print%28'Too%20cold!'%29
****
.Example {counter:python_intro_example} - If-Elif-Else Statements
--
--
* Even though several of the Boolean expressions are true when temp = 83, only the block after the first such expression executes.
* Try several different values of temp and see what is printed.

include::python_tutor.adoc[]
****

== While Statements
Python can execute a block repeatedly using a while statement and a Boolean expression.  The block repeats until the Boolean expression is false.

:pt_code_height: 300
:pt_rawinput: false
:pt_code: num%20%3D%205%0Awhile%20num%20%3E%200%3A%0A%20%20%20%20num%20%2B%3D%20-2%0A%20%20%20%20print%28num%29%0A
****
.Example {counter:python_intro_example} - While Statements
--
--
What numbers do you think will print? Notice that, without line 3, the loop would run forever.

include::python_tutor.adoc[]
****
NOTE: The += operator increases the value of the variable written to the left of the operator by the value written to the right of the operator.

== Lists and Loops
When you need to consider many values at once, use a list.

:pt_code_height: 320
:pt_rawinput: false
:pt_code: a%20%3D%20%5B15,%202,%2034,%2087%5D%0Ab%20%3D%20a%5B0%5D%20%23%20get%20the%20first%20value%20with%20index%200%0Ac%20%3D%20a%5B2%5D%20%23%20get%20the%20third%20valeu%20with%20index%202%0Ad%20%3D%20a%5B-1%5D%20%23%20get%20the%20last%20value%20with%20index%20-1%0Ae%20%3D%20len%28a%29%20%23%20the%20number%20of%20values
****
.Example {counter:python_intro_example} - List Indexing
--
--
Try index -2.

include::python_tutor.adoc[]
****

When you want to consider every value in a list, use a *for* loop.

:pt_code_height: 280
:pt_rawinput: false
:pt_code: nums%20%3D%20%5B10,%2030,%2020,%2050%5D%0Afor%20i%20in%20range%280,%20len%28nums%29%29%3A%0A%20%20%20%20print%28%22Index%22,%20i,%20%22Value%22,%20nums%5Bi%5D%29
****
.Example {counter:python_intro_example} - For Loops With Indices
--
--
* What does the variable i represent?
* What line creates the variable i?
* What line modifies it?

include::python_tutor.adoc[]
****

:pt_code_height: 280
:pt_rawinput: false
:pt_code: nums%20%3D%20%5B10,%2030,%2020,%2050%5D%0Afor%20x%20in%20nums%3A%0A%20%20%20%20print%28%22Value%22,%20x%29
NOTE: The range() function returns a sequence of numbers. The sequence starts at the value given by the first argument, increments by 1, and ends at one less than the value given by the second argument. For example, range(2,5) returns 2,3,4. If only one argument is given, that argument is considered the second argument and the first argument is set to 0 by default. For example, range(4) returns 0,1,2,3.
****
.Example {counter:python_intro_example} - For Loops Without Indices
--
--
* What line creates the variable x?
* What line modifies it?

include::python_tutor.adoc[]
****

:pt_code_height: 340
:pt_rawinput: false
:pt_code: grades%20%3D%20%5B99,%2088,%2095,%20101,%2065%5D%0Atotal%20%3D%200%0Afor%20g%20in%20grades%3A%0A%20%20%20%20total%20%2B%3D%20g%0Aavg%20%3D%20total%20//%20len%28grades%29%0Aprint%28%22Average%20is%22,%20avg%29%0A
****
.Example {counter:python_intro_example} - Summing with Loops
--
--
* What line creates the variable g?
* What line modifies it?

include::python_tutor.adoc[]
****

== List Appending and Slicing
We can append to lists with the concatenation operator (+). We can also slice a list using the bracket notation and two indices separated by a colon (:).
The first index specifies the starting point of the slice while the second index specifies the stopping point of the slice + 1.

video::TE6gg1p1eV4[youtube, 700, 500]

:pt_code_height: 340
:pt_rawinput: False
:pt_code: a+%3D+%5B%22Bob%22,+%22Lisa%22,+%22Tom%22%5D%0Ab+%3D+%5B%22Sally%22,+%22Sam%22%5D%0Ac+%3D+a+%2B+b%0Ac+%2B%3D+%5B%22John%22%5D%0Ad+%3D+c%5B0%3A2%5D%0Ae+%3D+c%5B-3%3A-1%5D&
****
.Example {counter:python_intro_example} - List Appending and Slicing
--
--
Try to predict the variable names, values, and data types in the code below. Use the _Next_ button to check your answers.

include::python_tutor.adoc[]
****

== Defining Custom Functions
In the examples above we have called several functions like print() and len().  You can define your own functions using *def*.  A function definition includes zero or more *parameter variables*. The values of those parameter variables are referred to as the *arguments* of the function.

:pt_code_height: 350
:pt_rawinput: false
:pt_code: def%20bob%28a,%20b%29%3A%0A%20%20%20%20c%20%3D%202%20*%20a%20%2B%20b%0A%20%20%20%20return%20c%0A%0Ax%20%3D%20bob%281,%202%29%0Ay%20%3D%20x%20%2B%20bob%28x,%203%29
****

// http://www.pythontutor.com/visualize.html#code=nums%20%3D%20%5B10,%2030,%2020,%2050%5D%0Afor%20i%20in%20range%280,%20len%28nums%29%29%3A%0A%20%20%20%20print%28%22Index%22,%20i,%20%22Value%22,%20nums%5Bi%5D%29&mode=edit&origin=opt-frontend.js&cumulative=false&heapPrimitives=false&textReferences=false&py=3&rawInputLstJSON=%5B%5D&curInstr=0

.Example {counter:python_intro_example} - Defining Functions
--
--
* What line creates the variables a and b?
* When does that line execute?
* How many times?
* Where do the variables a and b get their values from?

include::python_tutor.adoc[]
****

== Exercises

. Given the following Python code, what is the value and data type of each variable?
+
[source, Python]
----
a = 6 + 8
large = a // 4
b = 22 // 3
c = 22 % 3
d = False or True
e = True and False
sheep = (True or (b > 10))
----

. Given the following Python code, determine the printed output.
+
[source, Python]
----
print("Hello World!")
a = "The answer is"
b = 6 * 7
print(a, b)
print(False, "Hobbit", 1, "Ring")
----

. For the following code, determine the value of the variable letter when the score is 92, 84 and 59.
+
[source, Python]
----
score = #an interger between 0 and 100
if score >= 90:
	letter = 'A'
elif score >= 80:
	letter = 'B'
elif score >= 70:
	letter = 'C'
elif score >= 60:
	letter = 'D'
else:
	letter = 'F'
----

. For the following code, determine the value of the variable ans for each case given below.
+
[source, Python]
----
if outside == False:
	if (n >= 2 and n <= 20):
		return ans = True
	else:
		return ans = False
else:
	if (n <= 2 or n >= 20):
		return ans = True
	else:
		return ans = False
----

.. n = 3, outside = False
.. n = 15, outside = False
.. n = 15, outside = True
.. n = 12, outside = True

. What will this code print out?
+
[source, Python]
----
while count > 0:
	print("Welcome")
	count -= 1
----

. Write Python code to satisfy the following conditions. Then test your code on the values of the variables given.

.. Given an int n, return the absolute diffrence between n and 10, except return triple the absolute dfference if n is over 10. It should return 1 when n=9. It should return 33 when n=21.
What will the code return when n=7 or n=35?
.. We have a loud talking robot. The "hour" parameter is the current hour time in the range 0 to 23. We are in trouble if the robot is talking and the hour is before 6 or after 21. Return True if we are in trouble. It should return True when the robot is talking and the hour is 8. It should return False when the robot is not talking and the hour is 8. What does it return if the robot is talking and the hour is 9?

. What will the following code print out?
+
[source, Python]
----
numbers = [1, 3, 5, 7, 10]
sq = 0
for val in numbers:
	sq = val * val
	print(sq)
----

. What will the following code print out?
+
[source, Python]
----
for i in range(1, 20, 2):
	print(i)
----

. Use the following definition of the function front3() to find the output of the program for the list [1, 3, 5, 7].
+
[source, Python]
----
def front3(nums):
	i = 0
	while (i < len(nums) and i < 5):
		if nums[i] == 3:
			return True
		i += 1
	return False
----

. Write a function that takes, as input, two lists of integers, a and b, both of length 3, and returns, as output, a new list of length 2 containing the last elements of a and b. For example, if a = [1, 2, 3] and b = [10, 20, 30], then the function should return the list [3, 30].
